/- GENERATED by scripts/make_comparator_challenges.py from lean/ChargeLattice.lean.
   Do not edit by hand. Definitions are verbatim; proofs of listed theorems are `sorry`. -/
/-
  ChargeLattice.lean -- two cosmological charge lattices stated so that the kernel reads off the same
  distinction as `CompactBoson.lean`: the duality is a relabelling of the sectors; what the physics depends
  on is a function of the sector alone.

  Boundary note (added after a 2026-09-26 literature review): Moore's theorem N(D) = h(D) below is exact in the
  1/8-BPS K3 × T² setting this file states. It does NOT generalise unqualified to 1/4-BPS dyons on heterotic/T^6
  (a different setting): there, Dabholkar-Gaiotto-Nampuri (arXiv:hep-th/0702150) show the continuous-duality
  invariants alone "do not uniquely specify the state," an extra discrete invariant (gcd of the charges) is
  needed, and Sen (arXiv:0705.3874) shows the degeneracy further jumps across walls of marginal stability in
  moduli space. "Entropy is a function of the sector" is correct exactly as stated here (K3 × T², Moore's
  charges); it is not a general claim about every dyon-counting problem in string theory.

  Second boundary note (2026-09-26, same review): `disc_sl2_invariant` applies verbatim, with no new theorem,
  to a second physical setting -- the exact quarter-BPS D1-D5-P dyon lifted to 4D by an extra Kaluza-Klein-
  monopole charge. Sen's precision-counting review (arXiv:0708.1270, eq. 5.3.5-5.3.6) shows the exact
  microscopic degeneracy of that system is a function only of the T-duality invariants Q², P², Q·P of two
  charge vectors (Q, P) -- i.e. of Δ = Q²P² − (Q·P)², algebraically identical to D(p, q) above, with B taken
  to be the Narain bilinear form. `disc_sl2_invariant B hB hdet Q P` (this file, unchanged) already states
  Δ's SL(2, ℤ)-invariance for that instantiation; nothing further needed formalizing. What does NOT transfer:
  the class-number statement N(D) = h(D) above, since (per the first boundary note, Dabholkar-Gaiotto-Nampuri
  and Sen arXiv:0705.3874) Δ alone under-determines the state in this 4-charge setting -- no second Moore-style
  theorem is claimed. The historically prior Strominger-Vafa two-charge (hep-th/9601029) and Callan-Maldacena
  three-charge (hep-th/9602043) entropy formulas are explicitly OUT OF SCOPE for `disc`: their charge data
  (Q_H, Q_F, or Q1, Q5, n) is not a pair of vectors under one bilinear form, so no relabelling of `disc` covers
  them, and both formulas are leading-order Cardy approximations, not exact identities, by their own authors'
  statement.

  Part 1 -- the dyon charge lattice of type II on K3 × T² (Moore, "Arithmetic and attractors", 1998).
  A dyon is a pair (p, q) of vectors in an integral lattice Λ with a symmetric ℤ-bilinear form B
  (for K3 × T², Λ = II_{3,19} ⊕ ... ; we keep Λ abstract). The S-duality SL(2, ℤ) acts on the pair by
  (p, q) ↦ (a p + b q, c p + d q). Moore's discriminant
      D(p, q) = B(p,q)² − B(p,p) B(q,q)
  is what the horizon area depends on: A/4π = √(−D) in the supergravity approximation, and
  log dim H_BPS = π √(−D) + ⋯. The attractor mechanism fixes the K3 complex structure from (p, q) alone
  (Ω ∝ q − τ̄ p, τ = (p·q + √D)/p²) -- the moduli are OUTPUTS of the sector.
  * `disc_sl2_invariant`: D(a p + b q, c p + d q) = (a d − b c)² D(p, q); with a d − b c = 1 the discriminant
    is invariant. The duality permutes charge vectors inside a level set of D; the entropy reads the level set.
    Moore's count of U-duality-inequivalent dyons at fixed D is the class number h(D): the level set is
    not a single orbit, so D is a coarser invariant than the orbit -- the same map, different sectors, same
    physics.
  * `disc_scale`: D(t p, t q) = t⁴ D(p, q) -- the charge-scaling that the Strominger–Vafa asymptotics uses.
  * `disc_zero_of_parallel`: D(p, k p) = 0 -- a dyon whose electric and magnetic charges are parallel has no
    horizon in this approximation (the "small black hole"); parallelism is a sector property.

  Part 2 -- the flux-sector lattice of the cosmological constant (Bousso–Polchinski 2000; Kaloper 2025).
  With J four-form fluxes of charges q_i and integer quanta n_i,
      Λ(n) = Λ_bare + ½ Σ_i n_i² q_i².
  A membrane nucleation lowers one n_i by 1 and Λ by (n_i − ½) q_i². Kaloper's single dark top form has
  V(N) = ½ X ((1 − N) θ̂)², minimised exactly at the CP-invariant sector N = 1.
  * `bp_step`: the exact change of Λ under one nucleation of flux i.
  * `bp_step_neg_iff`: it lowers Λ iff n_i ≥ 1 -- the discharge sequence is monotone while the quanta are
    positive, which is why the Brown–Teitelboim/Bousso–Polchinski random walk moves inward.
  * `bp_min_at_zero`: with all q_i ≠ 0, Λ(n) ≥ Λ(0) with equality iff n = 0 -- the bare value is the floor of
    the lattice; the observed value is selected on the lattice, not produced by the lattice.
  * `kaloper_step`, `kaloper_min`, `kaloper_terminates`: each nucleation lowers V by X θ̂² (θ_dark − ½ θ̂) with
    θ_dark = (1 − N) θ̂ ; V is minimised at N = 1 where it vanishes; starting from N ≤ 1, after exactly 1 − N
    nucleations V = 0 -- the "discretely evanescent" dark energy ends at the CP-invariant sector.

  What this module says, and only this: on both lattices the observable (entropy; vacuum energy) is a function of
  the integer sector; the duality (Part 1) reindexes the lattice and preserves the function; the dynamics
  (Part 2) is a walk on the lattice whose steps and end point are fixed by the sector. Nothing here is a
  cosmological number, nothing is a claim about K3 surfaces beyond the algebra of the charge form, and nothing
  transfers a coupling from a superfluid. Whether the universe's Λ or a black hole's entropy IS such a function
  is the physical hypothesis the cited papers make; the module states what follows if it is.
-/
import Mathlib

namespace QuantumFluids.ChargeLattice

/-! ### Part 1 -- the dyon charge lattice and Moore's discriminant -/

section Dyon

variable {Λ : Type*} [AddCommGroup Λ] (B : LinearMap.BilinForm ℤ Λ)

/-- Moore's discriminant of a dyon `(p, q)`: `D = B(p,q)² − B(p,p) B(q,q)`. The horizon area is `√(−D)`. -/
def disc (p q : Λ) : ℤ := B p q ^ 2 - B p p * B q q

/-- Bilinearity spelled out on the S-duality image `(a p + b q, c p + d q)` -- the four Gram entries. -/
theorem gram_pp (hB : B.IsSymm) (a b : ℤ) (p q : Λ) :
    B (a • p + b • q) (a • p + b • q) = a ^ 2 * B p p + 2 * a * b * B p q + b ^ 2 * B q q := by
  sorry
theorem gram_pq (hB : B.IsSymm) (a b c d : ℤ) (p q : Λ) :
    B (a • p + b • q) (c • p + d • q)
      = a * c * B p p + (a * d + b * c) * B p q + b * d * B q q := by
  sorry
/-- **The discriminant is an S-duality invariant.** Under `(p, q) ↦ (a p + b q, c p + d q)`,
`D ↦ (a d − b c)² D`; for `SL(2, ℤ)` the factor is `1`. The duality relabels the dyons; the quantity the
horizon area and the BPS asymptotics depend on does not move. -/
theorem disc_sl2 (hB : B.IsSymm) (a b c d : ℤ) (p q : Λ) :
    disc B (a • p + b • q) (c • p + d • q) = (a * d - b * c) ^ 2 * disc B p q := by
  sorry
theorem disc_sl2_invariant (hB : B.IsSymm) {a b c d : ℤ} (hdet : a * d - b * c = 1) (p q : Λ) :
    disc B (a • p + b • q) (c • p + d • q) = disc B p q := by
  sorry
/-- The exchange `(p, q) ↦ (q, −p)` (the element `S` of `SL(2, ℤ)`, electric ↔ magnetic) preserves `D`. -/
theorem disc_electric_magnetic_swap (hB : B.IsSymm) (p q : Λ) : disc B q (-p) = disc B p q := by
  sorry
/-- Charge scaling: `D(t p, t q) = t⁴ D(p, q)` -- the large-charge asymptotics of Strominger–Vafa. -/
theorem disc_scale (hB : B.IsSymm) (t : ℤ) (p q : Λ) : disc B (t • p) (t • q) = t ^ 4 * disc B p q := by
  sorry
/-- A dyon with parallel electric and magnetic charges has `D = 0`: no horizon area at this order. -/
theorem disc_zero_of_parallel (hB : B.IsSymm) (k : ℤ) (p : Λ) : disc B p (k • p) = 0 := by
  sorry
/-- Over the reals (the supergravity regime `−D > 0`) the horizon area `√(−D)` is the same for every dyon in
an `SL(2, ℤ)` orbit. -/
theorem area_sl2_invariant (hB : B.IsSymm) {a b c d : ℤ} (hdet : a * d - b * c = 1) (p q : Λ) :
    Real.sqrt (-(disc B (a • p + b • q) (c • p + d • q) : ℝ)) = Real.sqrt (-(disc B p q : ℝ)) := by
  sorry
end Dyon

/-! ### Part 2 -- the flux-sector lattice of the vacuum energy -/

section Flux

/-- Bousso–Polchinski: `Λ(n) = Λ_bare + ½ Σ_i n_i² q_i²` over `J` four-form fluxes. -/
noncomputable def bpLambda {J : ℕ} (Λbare : ℝ) (q : Fin J → ℝ) (n : Fin J → ℤ) : ℝ :=
  Λbare + (1 / 2) * ∑ i, ((n i : ℝ) ^ 2 * q i ^ 2)

/-- One membrane nucleation of flux `i` lowers `n_i` by one and leaves the other quanta alone. -/
def nucleate {J : ℕ} (n : Fin J → ℤ) (i : Fin J) : Fin J → ℤ := Function.update n i (n i - 1)

/-- **The step**: `Λ(nucleate n i) − Λ(n) = −(n_i − ½) q_i²`. -/
theorem bp_step {J : ℕ} (Λbare : ℝ) (q : Fin J → ℝ) (n : Fin J → ℤ) (i : Fin J) :
    bpLambda Λbare q (nucleate n i) - bpLambda Λbare q n = -((n i : ℝ) - 1 / 2) * q i ^ 2 := by
  sorry
/-- The nucleation lowers `Λ` iff the flux quantum was positive. -/
theorem bp_step_neg_iff {J : ℕ} (Λbare : ℝ) (q : Fin J → ℝ) (n : Fin J → ℤ) (i : Fin J) (hq : q i ≠ 0) :
    bpLambda Λbare q (nucleate n i) < bpLambda Λbare q n ↔ 1 ≤ n i := by
  sorry
/-- The bare value is the floor of the flux lattice: `Λ(n) ≥ Λ(0)`. -/
theorem bp_ge_bare {J : ℕ} (Λbare : ℝ) (q : Fin J → ℝ) (n : Fin J → ℤ) :
    bpLambda Λbare q 0 ≤ bpLambda Λbare q n := by
  sorry
/-- With every charge non-zero, the floor is attained only at the zero sector. -/
theorem bp_min_at_zero {J : ℕ} (Λbare : ℝ) (q : Fin J → ℝ) (hq : ∀ i, q i ≠ 0) (n : Fin J → ℤ) :
    bpLambda Λbare q n = bpLambda Λbare q 0 ↔ n = 0 := by
  sorry
/-- Kaloper's dark top form: `V(N) = ½ X ((1 − N) θ̂)²`, the CP-violating phase in sector `N` being
`θ_dark = (1 − N) θ̂`. -/
noncomputable def kaloperV (X θ : ℝ) (N : ℤ) : ℝ := (1 / 2) * X * (((1 : ℝ) - N) * θ) ^ 2

/-- Each nucleation `N ↦ N + 1` lowers `V` by `X θ̂² (θ_dark − ½ θ̂)` with `θ_dark = (1 − N) θ̂`. -/
theorem kaloper_step (X θ : ℝ) (N : ℤ) :
    kaloperV X θ N - kaloperV X θ (N + 1) = X * θ ^ 2 * (((1 : ℝ) - N) - 1 / 2) := by
  sorry
/-- `V ≥ 0`, and `V = 0` exactly at the CP-invariant sector `N = 1` (for `X θ̂² ≠ 0`). -/
theorem kaloper_min (X θ : ℝ) (hX : 0 < X) (hθ : θ ≠ 0) (N : ℤ) :
    0 ≤ kaloperV X θ N ∧ (kaloperV X θ N = 0 ↔ N = 1) := by
  sorry
/-- **The discharge terminates at the CP-invariant sector**: from `N ≤ 1`, after exactly `1 − N` nucleations
the dark energy is zero. -/
theorem kaloper_terminates (X θ : ℝ) (N : ℤ) (hN : N ≤ 1) :
    kaloperV X θ (N + ((1 - N).toNat : ℤ)) = 0 := by
  sorry
end Flux

end QuantumFluids.ChargeLattice

-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)
