/- GENERATED by scripts/make_comparator_challenges.py from lean/ContinuumWinding.lean.
   Do not edit by hand. Definitions are verbatim; proofs of listed theorems are `sorry`. -/
/-
  ContinuumWinding.lean -- "Rome": the discrete winding number equals the continuum degree.

  `VortexWinding.lean` proves that the sampled loop sum of principal phase differences is an integer
  multiple of `2π`, and leaves open, explicitly, whether that integer is the TRUE topological charge of
  the continuum field ("a statement about sampling, not about the algorithm"). This file closes that
  gap for a closed loop of field values.

  * `pdiff_congr`          : the principal difference depends only on the two angles, not on the
                             representatives `arg` happens to return;
  * `sum_pdiff_telescope`  : when every true phase step is a principal value the loop sum telescopes to
                             the total phase change;
  * `discrete_eq_degree`   : for any continuous closed loop of ANGLES `γ : C(I, Real.Angle)` there is an
                             integer `w` (the degree: the total change of a continuous lift, divided by
                             `2π`) and a sampling threshold `n₀` such that, for every `n ≥ n₀` and every
                             choice of representatives of the `n` sampled angles, the discrete loop sum
                             is exactly `2π w`. The lift is Mathlib's path lifting through the covering
                             `ℝ → ℝ/2πℤ`; the threshold comes from Heine–Cantor;
  * `detector_correct`     : for a continuous, nowhere-vanishing, closed loop of FIELD VALUES
                             `c : C(I, ℂ)`, the phase-winding detector applied to `arg (c (i/n))`
                             returns `2π w` for all `n ≥ n₀`.

  What this settles: the number a GPE code computes around a plaquette is the degree of `ψ/|ψ|`
  along that plaquette's boundary, once the grid resolves the phase (no true step of size ≥ π). What
  a phase slip is in the continuum: the hypothesis `c t ≠ 0` failing -- a zero of `ψ` on the loop,
  where the angle loop, and with it the lift and the degree, cease to exist.

  NOT PROVED: any statement about the field OFF the loop (that the degree counts zeros inside, the
  argument principle) -- Mathlib's pinned version has no argument principle for general continuous
  maps, and the plaquette-additivity of `ScaleResolvedWinding.lean` is the discrete substitute; any
  quantitative link between the grid spacing and `n₀` (that needs a modulus of continuity of `ψ`).
-/
import VortexWinding
import QuantizedCirculation

namespace QuantumFluids.ContinuumWinding

open Real QuantumFluids.VortexWinding unitInterval

/-- The principal difference sees only the angles. -/
theorem pdiff_congr {a a' b b' : ℝ} (ha : (a : Real.Angle) = a') (hb : (b : Real.Angle) = b') :
    pdiff a b = pdiff a' b' := by
  sorry
/-- When every true step is a principal value, the loop sum telescopes to the total change. -/
theorem sum_pdiff_telescope (Γ : ℕ → ℝ) (n : ℕ) (h : ∀ i < n, Γ (i + 1) - Γ i ∈ Set.Ioc (-π) π) :
    ∑ i ∈ Finset.range n, pdiff (Γ i) (Γ (i + 1)) = Γ n - Γ 0 := by
  sorry
/-- Two reals with the same angle differ by an integer number of turns. -/
theorem degree_int (x y : ℝ) (h : (x : Real.Angle) = y) : ∃ w : ℤ, x - y = (w : ℝ) * (2 * π) := by
  sorry
/-- The `i`-th of `n` uniform sample points of the unit interval. -/
noncomputable def sample (n i : ℕ) : I := Set.projIcc 0 1 zero_le_one ((i : ℝ) / n)

theorem sample_zero (n : ℕ) : sample n 0 = 0 := by
  sorry
theorem sample_self (n : ℕ) (hn : 0 < n) : sample n n = 1 := by
  sorry
theorem sample_val (n i : ℕ) (hi : i ≤ n) (hn : 0 < n) : (sample n i : ℝ) = (i : ℝ) / n := by
  sorry
/-- Consecutive samples are `1/n` apart. -/
theorem dist_sample (n i : ℕ) (hi : i < n) :
    dist (sample n (i + 1)) (sample n i) = 1 / n := by
  sorry
local instance : Fact ((0 : ℝ) < 2 * π) := ⟨Real.two_pi_pos⟩

/-- **The discrete winding number is the degree.** -/
theorem discrete_eq_degree (γ : C(I, Real.Angle)) (hclosed : γ 1 = γ 0) :
    ∃ w : ℤ, ∃ n₀ : ℕ, 0 < n₀ ∧ ∀ n ≥ n₀, ∀ θ : ℕ → ℝ,
      (∀ i ≤ n, (θ i : Real.Angle) = γ (sample n i)) →
      ∑ i ∈ Finset.range n, pdiff (θ i) (θ (i + 1)) = (w : ℝ) * (2 * π) := by
  sorry
/-- **The phase-winding vortex detector is correct.** For a continuous, nowhere-vanishing, closed loop
of field values, the sampled principal-branch loop sum of `arg` equals `2π` times the degree of the
loop, for every fine enough uniform sampling. -/
theorem detector_correct (c : C(I, ℂ)) (hne : ∀ t, c t ≠ 0) (hclosed : c 1 = c 0) :
    ∃ w : ℤ, ∃ n₀ : ℕ, 0 < n₀ ∧ ∀ n ≥ n₀,
      ∑ i ∈ Finset.range n, pdiff (Complex.arg (c (sample n i))) (Complex.arg (c (sample n (i + 1))))
        = (w : ℝ) * (2 * π) := by
  sorry
end QuantumFluids.ContinuumWinding

-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)
