/- GENERATED by scripts/make_comparator_challenges.py from lean/TopologicalProtection.lean.
   Do not edit by hand. Definitions are verbatim; proofs of listed theorems are `sorry`. -/
/-
  TopologicalProtection.lean -- why a winding number can act as a CAUSE: it is conserved by every
  evolution that avoids a phase slip, so it is a memory the dynamics cannot erase continuously.

  `VortexWinding.loop_sum_eq_mul` and `QuantizedCirculation` prove that the loop sum of principal phase
  differences is `2π` times an integer (quantization). Quantization alone does not make topology
  causal: an integer that could jump freely would carry no memory. What makes it causal is
  conservation. This file proves conservation, discrete and continuous:

  * `pdiff_shift`           : moving the two endpoint phases by `δa`, `δb` moves the principal
                              difference by `δb - δa`, as long as the result stays in `(-π, π]`;
  * `loop_sum_stable`       : a perturbation `δ` of the loop phases leaves the loop sum (hence the
                              winding number) unchanged, provided no edge is pushed through the branch
                              point -- the quantitative form of "small perturbations cannot change
                              topology";
  * `loop_sum_stable_of_small` : an explicit sufficient condition: every `|δ i| < ε` and every edge step
                              `|pdiff| < π - 2ε`;
  * `circulation_conserved` : the same for the superfluid circulation (a discrete Kelvin theorem whose
                              only ingredient is topology);
  * `loop_sum_const_of_no_slip` : **continuous-time protection.** For phases depending continuously on
                              time, if no edge step ever reaches the branch point `π` on `[t₀, t₁]`,
                              the loop sum at `t₁` equals the loop sum at `t₀`;
  * `slip_of_winding_change`: contrapositive: if the winding changed, some edge step hit `π` at some
                              intermediate time -- a phase slip (Anderson, RMP 38, 298 (1966)).
                              In the continuum limit, that is the passage of a zero of `ψ`, a vortex
                              core, across the loop.

  Negative control (in the scratch file of the round, not here): the stability statement is false
  without its hypothesis; `quarterLoop`-type examples show a winding change when one edge crosses `π`.

  NOT PROVED: the continuum limit (that a discrete edge step reaching `π` corresponds to a zero of a
  smooth `ψ` crossing the loop); anything about energy barriers or rates of phase slips.
-/
import VortexWinding
import QuantizedCirculation

namespace QuantumFluids.TopologicalProtection

open Real QuantumFluids.VortexWinding

/-- Shifting both endpoints moves the principal difference by the difference of the shifts, as long
as the shifted value is still a principal value. -/
theorem pdiff_shift (a b da db : ℝ) (h : pdiff a b + (db - da) ∈ Set.Ioc (-π) π) :
    pdiff (a + da) (b + db) = pdiff a b + (db - da) := by
  sorry
/-- **Stability of the winding number.** If no edge is pushed through the branch point, the loop sum
of principal differences is unchanged by the perturbation `δ`. -/
theorem loop_sum_stable (θ δ : ℕ → ℝ) (n : ℕ) (hδ : δ n = δ 0)
    (h : ∀ i < n, pdiff (θ i) (θ (i + 1)) + (δ (i + 1) - δ i) ∈ Set.Ioc (-π) π) :
    ∑ i ∈ Finset.range n, pdiff (θ i + δ i) (θ (i + 1) + δ (i + 1))
      = ∑ i ∈ Finset.range n, pdiff (θ i) (θ (i + 1)) := by
  sorry
/-- An explicit sufficient condition: perturbations smaller than `ε` at every site cannot change the
winding of a loop whose every edge step is below `π - 2ε`. -/
theorem loop_sum_stable_of_small (θ δ : ℕ → ℝ) (n : ℕ) (ε : ℝ) (hδ : δ n = δ 0)
    (hsmall : ∀ i ≤ n, |δ i| < ε) (hedge : ∀ i < n, |pdiff (θ i) (θ (i + 1))| < π - 2 * ε) :
    ∑ i ∈ Finset.range n, pdiff (θ i + δ i) (θ (i + 1) + δ (i + 1))
      = ∑ i ∈ Finset.range n, pdiff (θ i) (θ (i + 1)) := by
  sorry
/-- **A discrete Kelvin theorem from topology alone.** Under the same no-slip condition the
superfluid circulation around the loop is conserved. -/
theorem circulation_conserved (hbar m : ℝ) (θ δ : ℕ → ℝ) (n : ℕ) (hδ : δ n = δ 0)
    (h : ∀ i < n, pdiff (θ i) (θ (i + 1)) + (δ (i + 1) - δ i) ∈ Set.Ioc (-π) π) :
    Circulation.circulation hbar m (fun i => θ i + δ i) n = Circulation.circulation hbar m θ n := by
  sorry
/-- `pdiff` is continuous in its arguments wherever the principal value is not the branch point `π`. -/
theorem continuousAt_pdiff {a b : ℝ} (h : pdiff a b ≠ π) :
    ContinuousAt (fun p : ℝ × ℝ => pdiff p.1 p.2) (a, b) := by
  sorry
/-- The loop sum, as a function of time. -/
noncomputable def loopSum (θ : ℝ → ℕ → ℝ) (n : ℕ) (t : ℝ) : ℝ :=
  ∑ i ∈ Finset.range n, pdiff (θ t i) (θ t (i + 1))

/-- **Continuous-time topological protection.** If every site phase depends continuously on time,
the loop is closed at every time, and no edge step reaches the branch point `π` during `[t₀, t₁]`,
then the loop sum -- `2π` times the winding number -- is the same at `t₁` as at `t₀`. -/
theorem loop_sum_const_of_no_slip (θ : ℝ → ℕ → ℝ) (n : ℕ) {t₀ t₁ : ℝ} (ht : t₀ ≤ t₁)
    (hcont : ∀ i ≤ n, Continuous (fun t => θ t i))
    (hclosed : ∀ t, θ t n = θ t 0)
    (hslip : ∀ t ∈ Set.Icc t₀ t₁, ∀ i < n, pdiff (θ t i) (θ t (i + 1)) ≠ π) :
    loopSum θ n t₁ = loopSum θ n t₀ := by
  sorry
/-- **A change of topology requires a phase slip.** If the winding differs between `t₀` and `t₁`, some
edge step reached the branch point at some intermediate time. -/
theorem slip_of_winding_change (θ : ℝ → ℕ → ℝ) (n : ℕ) {t₀ t₁ : ℝ} (ht : t₀ ≤ t₁)
    (hcont : ∀ i ≤ n, Continuous (fun t => θ t i)) (hclosed : ∀ t, θ t n = θ t 0)
    (hchange : loopSum θ n t₁ ≠ loopSum θ n t₀) :
    ∃ t ∈ Set.Icc t₀ t₁, ∃ i < n, pdiff (θ t i) (θ t (i + 1)) = π := by
  sorry
/-! ### The barrier: on an XY ring a phase slip costs a finite energy (mountain pass)

The XY ring `E = -J Σ cos(θ_{i+1} - θ_i)` is the lattice model of a superfluid ring (and the classical
model whose 2D version has the BKT transition). Protection needs more than conservation: it needs the
forbidden event to cost energy. It does: at the moment of the slip one bond sits at `π`, where it
contributes `+J` instead of at least `-J`. -/

/-- XY energy of a ring of `n` sites. -/
noncomputable def xyEnergy (J : ℝ) (θ : ℕ → ℝ) (n : ℕ) : ℝ :=
  -J * ∑ i ∈ Finset.range n, Real.cos (θ (i + 1) - θ i)

/-- The bond energy only sees the phase difference modulo `2π`. -/
theorem cos_pdiff (a b : ℝ) : Real.cos (pdiff a b) = Real.cos (b - a) := by
  sorry
/-- **Energy at a phase slip.** If one bond of the ring sits at the branch point `π`, the XY energy is
at least `-(n - 2) J`. -/
theorem slip_energy_ge (J : ℝ) (hJ : 0 ≤ J) (θ : ℕ → ℝ) (n j : ℕ) (hj : j < n)
    (hπ : pdiff (θ j) (θ (j + 1)) = π) :
    -((n : ℝ) - 2) * J ≤ xyEnergy J θ n := by
  sorry
/-- **Mountain pass for a phase slip.** Along any continuous evolution of the XY ring that changes the
winding number, the energy reaches at least `-(n - 2) J` at some intermediate time. -/
theorem mountain_pass (J : ℝ) (hJ : 0 ≤ J) (θ : ℝ → ℕ → ℝ) (n : ℕ) {t₀ t₁ : ℝ} (ht : t₀ ≤ t₁)
    (hcont : ∀ i ≤ n, Continuous (fun t => θ t i)) (hclosed : ∀ t, θ t n = θ t 0)
    (hchange : loopSum θ n t₁ ≠ loopSum θ n t₀) :
    ∃ t ∈ Set.Icc t₀ t₁, -((n : ℝ) - 2) * J ≤ xyEnergy J (θ t) n := by
  sorry
/-- The uniformly twisted ring `θ_i = 2π i / n` has winding one. -/
theorem twisted_loopSum (n : ℕ) (hn : 2 ≤ n) :
    ∑ i ∈ Finset.range n, pdiff (2 * π * i / n) (2 * π * (i + 1 : ℕ) / n) = 2 * π := by
  sorry
/-- Its XY energy is `-n J cos(2π/n)`. -/
theorem twisted_energy (J : ℝ) (n : ℕ) :
    xyEnergy J (fun i => 2 * π * i / n) n = -(n : ℝ) * J * Real.cos (2 * π / n) := by
  sorry
/-- **The barrier is positive for rings of at least 10 sites**: leaving the twisted winding-one state
by a phase slip costs at least `n J cos(2π/n) - (n-2) J ≥ 2J - 2π²J/n > 0`. So the winding is not
only conserved without slips; slips are activated, which is what makes a persistent current persist. -/
theorem barrier_pos (J : ℝ) (hJ : 0 < J) (n : ℕ) (hn : 10 ≤ n) :
    xyEnergy J (fun i => 2 * π * i / n) n < -((n : ℝ) - 2) * J := by
  sorry
end QuantumFluids.TopologicalProtection

-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)
