#!/usr/bin/env python3
"""Generate docs/REFERENCES.md from the papers' own .bib files.

The reference list is generated, never hand-edited, so it cannot drift from what the papers actually
cite. Entries are de-duplicated by key; when the same key appears in several .bib files with different
fields, the first file in BIBS order wins and the disagreement is reported on stderr.

    python3 scripts/make_references.py            # write docs/REFERENCES.md
    python3 scripts/make_references.py --check    # exit non-zero if docs/REFERENCES.md is stale
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BIBS = ["papers/refs_sector_thesis.bib", "papers/refs_duality_sector.bib", "papers/refs_cosmology_sectors.bib"]
OUT = ROOT / "docs" / "REFERENCES.md"
ENTRY = re.compile(r"@(\w+)\{([^,]+),(.*)\}\s*$")


def field(body: str, name: str) -> str | None:
    """Value of a top-level `name={...}` field, honouring nested braces."""
    m = re.search(rf"(?:^|,)\s*{name}\s*=\s*\{{", body)
    if not m:
        return None
    i, depth = m.end(), 1
    start = i
    while i < len(body) and depth:
        depth += {"{": 1, "}": -1}.get(body[i], 0)
        i += 1
    return body[start:i - 1].strip()


def clean(s: str) -> str:
    s = re.sub(r"\\['`^\"~]\{?(\w)\}?", r"\1", s)          # accents: \'e -> e
    s = s.replace("{", "").replace("}", "").replace("--", "–")
    return re.sub(r"\s+", " ", s).strip()


def main() -> None:
    entries: dict[str, dict] = {}
    origin: dict[str, str] = {}
    for rel in BIBS:
        for line in (ROOT / rel).read_text().splitlines():
            m = ENTRY.match(line.strip())
            if not m:
                continue
            kind, key, body = m.group(1), m.group(2).strip(), m.group(3)
            rec = {f: field(body, f) for f in ("author", "title", "journal", "volume", "pages", "year",
                                                 "doi", "eprint", "howpublished")}
            if key in entries:
                if rec["doi"] != entries[key]["doi"]:
                    print(f"note: {key} differs between {origin[key]} and {rel} (doi "
                          f"{entries[key]['doi']} vs {rec['doi']}); keeping {origin[key]}", file=sys.stderr)
                continue
            entries[key], origin[key] = rec, rel

    own = {k: v for k, v in entries.items() if k.startswith("Callens")}
    ext = {k: v for k, v in entries.items() if not k.startswith("Callens")}

    def line(rec: dict) -> str:
        parts = [clean(rec["author"] or ""), f"*{clean(rec['title'] or '')}*"]
        venue = " ".join(x for x in [clean(rec["journal"] or ""), rec["volume"] or "",
                                      clean(rec["pages"] or "")] if x)
        if venue:
            parts.append(venue)
        if rec["year"]:
            parts.append(f"({rec['year']})")
        link = ""
        if rec["doi"]:
            link = f"[doi:{rec['doi']}](https://doi.org/{rec['doi']})"
        elif rec["eprint"]:
            link = f"[arXiv:{rec['eprint']}](https://arxiv.org/abs/{rec['eprint']})"
        return "- " + ", ".join(p for p in parts if p) + (f". {link}" if link else ".")

    key_sort = lambda kv: (clean(kv[1]["author"] or kv[0]).lower(), kv[1]["year"] or "")
    out = ["# References", "",
           "Generated by `scripts/make_references.py` from the `.bib` files in `papers/` — do not edit by",
           "hand. Every entry was verified against Crossref or its source before it entered a `.bib`",
           "file (the programme's literature gate).", "",
           "## This programme's own archived works", "",
           "The foundation paper of this theory has its own dedicated DOI:",
           "[10.5281/zenodo.22985863](https://doi.org/10.5281/zenodo.22985863) (concept DOI). The software",
           "archive of the origin programme, including every companion paper:",
           "[10.5281/zenodo.22855581](https://doi.org/10.5281/zenodo.22855581) (concept DOI). Version DOIs cited",
           "inside individual papers below point to the release current when that paper was written.", ""]
    out += [line(v) for _, v in sorted(own.items(), key=key_sort)]
    out += ["", f"## Cited literature ({len(ext)} works)", ""]
    out += [line(v) for _, v in sorted(ext.items(), key=key_sort)]
    text = "\n".join(out) + "\n"

    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit("docs/REFERENCES.md is stale: run python3 scripts/make_references.py")
        print("docs/REFERENCES.md is up to date")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(own)} own works, {len(ext)} cited works")


if __name__ == "__main__":
    main()
