#!/usr/bin/env python3
"""Regenerate the `#print axioms` block of every Lean file so it covers EVERY theorem.

Why this exists. The audit blocks were maintained by hand and drifted: an external review of the
v1.1.0 tag found `DualLength.lean` declaring 13 theorems while the reported count was 12. Checking
all files showed the problem was wider -- 77 theorems against 65 audit lines, so 12 theorems had
never been axiom-audited and the reported totals were conflating "theorems" with "theorems carrying
an audit line". A hand-kept list will drift again; a generator will not.

Run:    python3 scripts/regen_axiom_audit.py [--check]
        --check exits non-zero if any file is out of date (for CI / verify.sh).
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent / "lean"
SKIP = {"lakefile.lean", "SectorCausality.lean"}   # umbrella: imports only
DECL = re.compile(r"^(?:private\s+)?(?:theorem|lemma)\s+([A-Za-z_][A-Za-z0-9_'!?]*)", re.M)
NS = re.compile(r"^namespace\s+(\S+)", re.M)
MARKER = "-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)"


def names(text: str) -> list[str]:
    """Theorem names in declaration order, de-duplicated."""
    seen, out = set(), []
    for m in DECL.finditer(text):
        n = m.group(1)
        if n not in seen:
            seen.add(n)
            out.append(n)
    return out


def rebuild(path: Path) -> tuple[str, int]:
    text = path.read_text()
    body = text.split(MARKER)[0].rstrip("\n")
    # drop any pre-existing hand-written audit lines
    body = "\n".join(l for l in body.split("\n") if not l.startswith("#print axioms")).rstrip("\n")
    ns_m = NS.search(body)
    prefix = (ns_m.group(1) + ".") if ns_m else ""
    thms = names(body)
    block = "\n".join(f"#print axioms {prefix}{n}" for n in thms)
    return f"{body}\n\n{MARKER}\n{block}\n", len(thms)


def main() -> int:
    check = "--check" in sys.argv
    stale, total = [], 0
    for path in sorted(SRC.glob("*.lean")):
        if path.name in SKIP:
            continue
        new, n = rebuild(path)
        total += n
        if new != path.read_text():
            stale.append(path.name)
            if not check:
                path.write_text(new)
        print(f"  {path.name:<28} {n:>3} theorems")
    print(f"total: {total} theorems")
    if check and stale:
        print(f"OUT OF DATE: {', '.join(stale)} -- run scripts/regen_axiom_audit.py", file=sys.stderr)
        return 1
    if stale and not check:
        print(f"rewrote: {', '.join(stale)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
