import Lake
open Lake DSL

package sectorCausality

/-- `import SectorCausality` gives the whole library: every machine-checked module behind
"Duality is a structure; the sector is the cause" and its companion papers. Self-contained --
this package does not depend on the SocrateAI-Scientific-QuantumFluids repository it was
extracted from; it pins the same Mathlib revision independently. -/
@[default_target]
lean_lib SectorCausality

/-- Mathlib pinned to tag v4.34.0-rc2, the same revision the source repository (SocrateAI-
Scientific-QuantumFluids) uses, so theorem statements and axiom footprints match exactly. -/
require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git" @ "85e3a25e006c35636f0e53b0e9296caca2685bc0"  -- tag v4.34.0-rc2

@[default_target]
lean_lib VortexWinding

@[default_target]
lean_lib QuantizedCirculation

@[default_target]
lean_lib DualLength

@[default_target]
lean_lib Fricke

@[default_target]
lean_lib QHFricke

@[default_target]
lean_lib TopologicalProtection

@[default_target]
lean_lib ScaleResolvedWinding

@[default_target]
lean_lib ContinuumWinding

@[default_target]
lean_lib SectorTemperature

@[default_target]
lean_lib CompactBoson

@[default_target]
lean_lib ChargeLattice

@[default_target]
lean_lib SectorDuality

@[default_target]
lean_lib RCFTDuality

@[default_target]
lean_lib LevelRankDuality

/-- Comparator challenge statements (generated by `scripts/make_comparator_challenges.py`).
NOT a default target: they contain `sorry` by design and must never count as built theorems.
Built on demand by `comparator`, which names the module in its JSON config. -/
lean_lib ComparatorChallenges where
  globs := #[.submodules `ComparatorChallenges]
