/-
  LevelRankDuality.lean -- a seventh cross-domain case: level-rank duality of Chern-Simons/WZW theories,
  U(N)_K <-> U(K)_N (Naculich-Schnitzer 2007, DOI 10.1088/1126-6708/2007/06/023; Hsin-Seiberg 2016,
  DOI 10.1007/JHEP09(2016)095), stated at the level of its combinatorial skeleton.

  Background. The integrable highest-weight primaries of U(N) at level K are labelled by Young diagrams
  fitting in an N-row, K-column box; level-rank duality relabels U(N)_K's primaries by U(K)_N's via
  transposition of that box (an N x K box <-> a K x N box). This is the SECTOR of a further duality in
  the fractional-quantum-Hall/Chern-Simons setting already touched by `QHFricke.lean` (Lutken-Ross's
  Gamma_0(2) on the Hall conductivity plane) -- a DIFFERENT duality, acting on a different sector (the
  finite set of anyon/primary labels, not the Chern integer), in the "organisation, not cause" slot: it
  is a proved finite relabelling of a label set that decides no physics and causes no transition. Son's
  2015 particle-vortex duality at nu = 1/2 (Phys. Rev. X 5, 031027) and Seiberg-Senthil-Wang-Witten's
  2016 duality web (Annals Phys. 374, 395) are the field-theoretic (non-topological, non-rigorous) layer
  ABOVE this; level-rank duality is their rigorously-established topological limit once matter is gapped
  and integrated out.

  What this module proves: the finite combinatorial skeleton only -- that a Young diagram fits in an
  a-row, b-column box iff its transpose fits in a b-row, a-column box, packaged as an `Equiv` between
  the two (finite) label sets, using Mathlib's own `YoungDiagram.transpose`/`transposeOrderIso`
  (no re-derivation). What it does NOT prove -- and no elementary Lean tactic could, without affine-Lie-
  algebra representation theory or modular-tensor-category machinery Mathlib does not have -- is the
  actual physical content of level-rank duality: that the modular S,T matrices (hence the Verlinde
  fusion coefficients, `RCFTDuality.lean`'s object) match across the two theories. This module states
  only the LABEL bijection; the S,T-matrix identification is prose, exactly as `RCFTDuality.lean`'s
  su(2) level-1 identification and `SectorDuality.lean`'s Z_N-Fourier-is-Kramers-Wannier identification
  are prose, not something the type checker verifies.

  * `inBox`                : a Young diagram fits in `a` rows and `b` columns;
  * `inBox_transpose_iff`  : `mu` fits in an `a x b` box iff `mu.transpose` fits in a `b x a` box;
  * `levelRankRelabeling`  : the induced bijection between the two (sub)sets of Young diagrams -- the
                             level-rank primary-label relabelling, as a checked `Equiv`.
-/
import Mathlib

namespace QuantumFluids.LevelRankDuality

open YoungDiagram

/-- A Young diagram fits in a box of `a` rows and `b` columns: no more than `a` rows (its 0th column,
i.e. tallest column, has length `<= a`) and each row has length `<= b` (equivalently, by `rowLen_anti`,
its widest row -- row 0 -- has length `<= b`). -/
def inBox (a b : ℕ) (μ : YoungDiagram) : Prop := μ.colLen 0 ≤ a ∧ μ.rowLen 0 ≤ b

/-- **The level-rank box swap**: `mu` fits in an `a x b` box iff its transpose fits in a `b x a` box --
the statement, at the level of labels, that a U(N)_K primary (a Young diagram in an `N x K` box)
corresponds to a U(K)_N primary (a Young diagram in a `K x N` box) under transposition. -/
theorem inBox_transpose_iff (a b : ℕ) (μ : YoungDiagram) :
    inBox a b μ ↔ inBox b a μ.transpose := by
  unfold inBox
  rw [YoungDiagram.colLen_transpose, YoungDiagram.rowLen_transpose]
  exact and_comm

/-- **The level-rank relabelling as a bijection**: the primaries of `U(N)_K` (Young diagrams in an
`a x b` box, `a = N`, `b = K`) are in bijection with the primaries of `U(K)_N` (Young diagrams in a
`b x a` box), via `YoungDiagram.transpose`. This certifies the finite relabelling is a genuine
bijection of the label sets; it says nothing about the modular data (S, T matrices) the physical
duality also identifies. -/
def levelRankRelabeling (a b : ℕ) : { μ : YoungDiagram // inBox a b μ } ≃ { μ : YoungDiagram // inBox b a μ } :=
  Equiv.subtypeEquiv YoungDiagram.transposeOrderIso.toEquiv (fun μ => by
    simpa [YoungDiagram.transposeOrderIso_apply] using inBox_transpose_iff a b μ)

end QuantumFluids.LevelRankDuality

-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)
#print axioms QuantumFluids.LevelRankDuality.inBox_transpose_iff
