/-
  QHFricke.lean -- where the Fricke involution of `Fricke.lean` meets the quantum Hall modular group,
  and where it stops. Gate verdict 3 of `docs/designs/PGPE_BKT_PREREG.md` amendment A2.

  Background (Lütken–Ross, PRB 45, 11837 (1992); review arXiv:1008.5257): for the spin-polarised
  quantum Hall system the holomorphic part of the proposed emergent symmetry acting on the complex
  conductivity `σ = σ_xy + i σ_xx` (units e²/h) is `Γ₀(2)`, generated by `T : σ ↦ σ + 1` and
  `D = S T² S : σ ↦ σ/(1 − 2σ)`. Plateaux sit at rationals `p/q` with `q` odd; the delocalisation
  critical point between the `ν = 0` and `ν = 1` plateaux is `σ⊗ = (1+i)/2`.

  Proved here, as arithmetic of Möbius maps, with no physics attached:

  * `M_mem_Gamma0` / `M_mul_M` / `M_fixes_crit` : `M = (1, -1; 2, -1)` lies in `Γ₀(2)`, squares to `-1`
    (an elliptic element, order 2 in `PSL(2,ℤ)`), and fixes `σ⊗ = (1+i)/2`;
  * `gamma0_two_odd_den` : every matrix with even lower-left entry and determinant 1 sends an
    odd-denominator fraction to an odd-denominator fraction -- `Γ₀(2)` preserves the plateau class;
  * `fricke_crit` : the level-2 Fricke map `σ ↦ -1/(2σ)` sends `σ⊗` to `σ⊗ - 1 = T⁻¹ σ⊗`, so on the
    quotient `Γ₀(2)\H` it FIXES the critical point's orbit (with `fricke_on_axis`'s `i/√2`, one of the
    two fixed points of `w₂` on `X₀(2)`; that there are exactly two is classical and not proved here);
  * `fricke_plateau_not_plateau` : but the Fricke map sends every plateau `p/q` (`q` odd, `p ≠ 0`) to
    `-q/(2p)`, which equals NO fraction with an odd denominator. So `w₂` is not a symmetry of the
    Hall phase diagram: it exchanges the cusp class that carries the plateaux with the one that
    carries none.

  NOT proved, NOT claimed: that `Γ₀(2)` is the symmetry of real Hall samples (that is Lütken–Ross's
  physical proposal, supported by data they review, not a theorem); anything about K3 surfaces;
  anything about helium or BKT.
-/
import Mathlib

open Matrix MatrixGroups CongruenceSubgroup

namespace QuantumFluids.QHFricke

/-- The Möbius action of an integer matrix on a complex number. -/
noncomputable def mob (a b c d : ℤ) (z : ℂ) : ℂ := ((a : ℂ) * z + b) / ((c : ℂ) * z + d)

/-- The quantum Hall critical point between the `ν = 0` and `ν = 1` plateaux. -/
noncomputable def crit : ℂ := (1 + Complex.I) / 2

/-- The elliptic element of `Γ₀(2)` that fixes `crit`. -/
def M : SL(2, ℤ) := ⟨!![1, -1; 2, -1], by simp [Matrix.det_fin_two]⟩

theorem M_mem_Gamma0 : M ∈ Gamma0 2 := by
  rw [Gamma0_mem]; decide

/-- `M² = -1`: elliptic, of order 2 in `PSL(2,ℤ)`. -/
theorem M_mul_M : (M : Matrix (Fin 2) (Fin 2) ℤ) * M = -1 := by
  ext i j; fin_cases i <;> fin_cases j <;> simp [M, Matrix.mul_apply, Fin.sum_univ_two]

/-- `M` fixes the critical point `(1+i)/2`. -/
theorem M_fixes_crit : mob 1 (-1) 2 (-1) crit = crit := by
  unfold mob crit
  have h : (2 : ℂ) * ((1 + Complex.I) / 2) + -1 = Complex.I := by ring
  push_cast
  rw [h, div_eq_iff Complex.I_ne_zero]
  ring_nf; rw [Complex.I_sq]; ring

/-- `Γ₀(2)` preserves the class of odd-denominator fractions (the plateau class): if `c` is even and
`ad - bc = 1`, then `q` odd implies `c p + d q` odd. -/
theorem gamma0_two_odd_den (a b c d p q : ℤ) (hdet : a * d - b * c = 1) (hc : Even c) (hq : Odd q) :
    Odd (c * p + d * q) := by
  have hd : Odd d := by
    have had : Odd (a * d) := by
      have : a * d = 1 + b * c := by linarith
      rw [this]; exact Even.one_add (hc.mul_left b)
    exact (Int.odd_mul.1 had).2
  exact Even.add_odd (hc.mul_right p) (hd.mul hq)

/-- The level-2 Fricke map sends the critical point to its translate by `-1`, i.e. to `T⁻¹ crit`,
which is in the same `Γ₀(2)`-orbit: `w₂` fixes the critical point on `Γ₀(2)\H`. -/
theorem fricke_crit : mob 0 (-1) 2 0 crit = crit - 1 := by
  unfold mob crit
  have hne : (2 : ℂ) * ((1 + Complex.I) / 2) + 0 ≠ 0 := by
    rw [show (2 : ℂ) * ((1 + Complex.I) / 2) + 0 = 1 + Complex.I by ring]
    intro h; have := congrArg Complex.re h; simp at this
  push_cast
  rw [div_eq_iff hne]
  ring_nf; rw [Complex.I_sq]; ring

/-- **The Fricke map sends no plateau to a plateau.** For `q` odd and `p ≠ 0`, the image
`-1/(2 · (p/q)) = -q/(2p)` is not equal to any fraction `r/s` with `s` odd. -/
theorem fricke_plateau_not_plateau (p q r s : ℤ) (hp : p ≠ 0) (hq : Odd q) (hs : Odd s) :
    (r : ℚ) / s ≠ -(q : ℚ) / (2 * p) := by
  intro h
  have hs0 : (s : ℚ) ≠ 0 := by
    have : s ≠ 0 := by rintro rfl; have := Int.odd_iff.1 hs; omega
    exact_mod_cast this
  have hp0 : (2 * (p : ℚ)) ≠ 0 := by
    have : (p : ℚ) ≠ 0 := by exact_mod_cast hp
    exact mul_ne_zero two_ne_zero this
  rw [div_eq_div_iff hs0 hp0] at h
  have hz : r * (2 * p) = -q * s := by exact_mod_cast h
  have heven : Even (q * s) := by
    have : Even (r * (2 * p)) := (even_two_mul p).mul_left r
    rw [hz] at this
    simpa [neg_mul, even_neg] using this
  exact (Int.not_even_iff_odd.2 (hq.mul hs)) heven

end QuantumFluids.QHFricke

-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)
#print axioms QuantumFluids.QHFricke.M_mem_Gamma0
#print axioms QuantumFluids.QHFricke.M_mul_M
#print axioms QuantumFluids.QHFricke.M_fixes_crit
#print axioms QuantumFluids.QHFricke.gamma0_two_odd_den
#print axioms QuantumFluids.QHFricke.fricke_crit
#print axioms QuantumFluids.QHFricke.fricke_plateau_not_plateau
