/-
  RCFTDuality.lean -- a sixth cross-domain case for the criterion of `duality_sector.tex`: the modular
  S-matrix of a rational conformal field theory (RCFT), sharper than `SectorDuality.lean`'s Z_N case.

  Background (Verlinde 1980; Rev. Mod. Phys. -- no, Verlinde 1988, Nucl. Phys. B300; proved from
  Moore-Seiberg's polynomial equations, Phys. Lett. B212 1988 and Commun. Math. Phys. 123 1989): the
  Verlinde formula N_ij^k = sum_m S_im S_jm S*_km / S_0m makes the modular S-matrix acting on the RCFT's
  primaries (the sectors) a duality. Fuchs (hep-th/9306162, eq. 4.1-4.2) states the exact identity
  S^2 = C = (ST)^3 for S unitary and symmetric, C the charge-conjugation matrix -- sharper than
  `SectorDuality.lean`'s finite-cyclic case, where Mathlib's UNnormalised `ZMod.dft` gives
  `dft (dft Phi) = N • Phi(-.)`, not the identity.

  S is a literal finite-abelian-group Fourier transform only in the "pointed" (simple-current) case,
  where the fusion ring is a group -- e.g. su(2) level 1 (Kac-Peterson/Fuchs eq. 7.7), two primaries
  (spin 0 and spin 1/2), fusing as Z_2, with S_jk = n^{-1/2} exp(2 pi i m j k / n) for n = 2: this is
  exactly the (unnormalised) Hadamard matrix, and its square is 2 * (the identity) -- since both
  primaries are self-conjugate, C = 1, so the UNITARY (normalised) S satisfies S^2 = 1 exactly, with
  none of the decoupled factor |Z_2| = 2 that `SectorDuality.kramersWannier_gauging_sq` carries.

  What this module proves: a single, decidable 2x2 integer-matrix identity. What it does NOT prove --
  and no elementary Lean tactic could -- is that this matrix IS the su(2) level-1 Kac-Peterson S-matrix;
  that identification is representation theory of affine Lie algebras (Fuchs's derivation), supplied
  here as physics input in this docstring, exactly as `SectorDuality.lean` already treats the
  Z_N-Fourier-transform-is-Kramers-Wannier identification as prose, not as a fact the type checker
  verifies. Nor does this module touch the general (non-abelian) case, where S is the Kac-Peterson
  Weyl-sum matrix and no elementary group Fourier transform underlies it at all.

  Self-dual point (reading, not a theorem): the free boson at the T-duality self-dual radius R = 1
  enhances to su(2) level 1. Pace-Chatterjee-Shao (arXiv:2412.18606, Fig. 4) show this point sits on a
  *continuous* line of RCFT fixed points (1 <= R <= sqrt 2), separating three gapped phases -- by the
  criterion of `duality_sector.tex`, a point like any other on a line of fixed points, the same verdict
  already reached for the compact boson's own self-dual radius and for BKT, not the Ising verdict.

  * `su2Level1_S_sq`     : the unnormalised Hadamard/Kac-Peterson matrix squares to 2 * 1;
  * `su2Level1_S_symm`   : it is symmetric (S = S^T), as the Verlinde S-matrix must be;
  * `su2Level1_S_det`    : its determinant is -2 (negative controls fail: claiming it is 1 or -1).
-/
import Mathlib

namespace QuantumFluids.RCFTDuality

open Matrix

/-- The su(2) level-1 WZW modular S-matrix (Kac-Peterson), UNnormalised: entries are integers: the
unitary S is `(1 / Real.sqrt 2) • this`. The two rows/columns are indexed by the primaries spin 0 and
spin 1/2. -/
def su2Level1_S : Matrix (Fin 2) (Fin 2) ℤ := !![1, 1; 1, -1]

/-- **The Verlinde relation `S² = C` for su(2)₁**: since both primaries are self-conjugate, `C = 1`,
and the unnormalised identity reads `S² = 2 • 1` (the factor `|Z₂| = 2` is exactly the normalisation
`1/√2` per row that the unitary Verlinde S-matrix carries and this integer matrix omits). -/
theorem su2Level1_S_sq : su2Level1_S * su2Level1_S = (2 : ℤ) • (1 : Matrix (Fin 2) (Fin 2) ℤ) := by
  unfold su2Level1_S; decide

/-- The Verlinde S-matrix is symmetric. -/
theorem su2Level1_S_symm : su2Level1_S.transpose = su2Level1_S := by
  unfold su2Level1_S; decide

/-- Its determinant is `-2` (so it is invertible over ℚ, as a duality must be). -/
theorem su2Level1_S_det : su2Level1_S.det = -2 := by
  unfold su2Level1_S; decide

end QuantumFluids.RCFTDuality

-- BEGIN axiom audit (generated by scripts/regen_axiom_audit.py -- do not edit by hand)
#print axioms QuantumFluids.RCFTDuality.su2Level1_S_sq
#print axioms QuantumFluids.RCFTDuality.su2Level1_S_symm
#print axioms QuantumFluids.RCFTDuality.su2Level1_S_det
